import 'package:flutter/material.dart';
import 'package:readmore/readmore.dart';

class PrivacyPolicy extends StatelessWidget {
  PrivacyPolicy({super.key});
  String content =
      "Shelvin Varghese built the Mio Mix app as a Free app. This SERVICE is provided by Shelvin Varghese at no cost and is intended for use as is.This page is used to inform visitors regarding my policies with the collection, use, and disclosure of Personal Information if anyone decided to use my Service.If you choose to use my Service, then you agree to the collection and use of information in relation to this policy. The Personal Information that I collect is used for providing and improving the Service. I will not use or share your information with anyone except as described in this Privacy Policy.\nThe terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, which are accessible at Shelvin Varghese unless otherwise defined in this Privacy Policy.";
  String content1 =
      " For a better experience, while using our Service, I may require you to provide us with certain personally identifiable information, including but not limited to tall man,. The information that I request will be retained on your device and is not collected by me in any way.\nThe app does use third-party services that may collect information used to identify you.";
  String content2 =
      "Cookies are files with a small amount of data that are commonly used as anonymous unique identifiers. These are sent to your browser from the websites that you visit and are stored on your device's internal memory.\nThis Service does not use these “cookies” explicitly. However, the app may use third-party code and libraries that use “cookies” to collect information and improve their services. You have the option to either accept or refuse these cookies and know when a cookie is being sent to your device. If you choose to refuse our cookies, you may not be able to use some portions of this Service.";
  String content3 =
      "If you have any questions or suggestions about my Privacy Policy, do not hesitate to contact me at shelvinvarghese6@gmail.com.\nThis privacy policy page was created at privacypolicytemplate.net and modified/generated by App Privacy Policy Generator";
  @override
  Widget build(BuildContext context) {
    final height1 = MediaQuery.of(context).size.height;
    final width1 = MediaQuery.of(context).size.width;
    return Scaffold(
      backgroundColor: const Color.fromARGB(255, 23, 63, 97),
      body: SafeArea(
        child: Column(
          children: [
            Container(
              width: width1 * 1,
              height: height1 * 0.10,
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(18),
                color: Colors.black26,
              ),
              child: Column(
                children: [
                  Row(
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      Padding(
                        padding: EdgeInsets.symmetric(
                            horizontal: width1 * 0.05,
                            vertical: height1 * 0.02),
                        child: const Text(
                          'Privacy Policy',
                          style: TextStyle(
                              color: Colors.white,
                              fontSize: 32,
                              fontWeight: FontWeight.bold),
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),
            Expanded(
              child: SingleChildScrollView(
                child: Column(
                  children: [
                    Container(
                      padding: EdgeInsets.all(15),
                      child: ReadMoreText(
                        content,
                        trimLines: 58,
                        textAlign: TextAlign.justify,
                        trimMode: TrimMode.Line,
                        lessStyle: const TextStyle(
                          fontWeight: FontWeight.bold,
                          color: Colors.white,
                        ),
                        moreStyle: const TextStyle(
                          fontWeight: FontWeight.bold,
                          color: Colors.white,
                        ),
                        style: const TextStyle(
                            fontSize: 16, height: 1.5, color: Colors.white),
                      ),
                    ),
                    Row(
                      children: [
                        SizedBox(
                          width: width1 * 0.04,
                        ),
                        const Text(
                          'Information Collection and Use',
                          style: TextStyle(
                              color: Colors.white,
                              fontSize: 20,
                              fontWeight: FontWeight.bold),
                        )
                      ],
                    ),
                    Container(
                      padding: const EdgeInsets.all(15),
                      child: ReadMoreText(
                        content1,
                        trimLines: 58,
                        textAlign: TextAlign.justify,
                        trimMode: TrimMode.Line,
                        lessStyle: const TextStyle(
                          fontWeight: FontWeight.bold,
                          color: Colors.white,
                        ),
                        moreStyle: const TextStyle(
                          fontWeight: FontWeight.bold,
                          color: Colors.white,
                        ),
                        style: const TextStyle(
                            fontSize: 16, height: 1.5, color: Colors.white),
                      ),
                    ),
                    Row(
                      children: [
                        SizedBox(
                          width: width1 * 0.04,
                        ),
                        const Text(
                          'Cookies',
                          style: TextStyle(
                              color: Colors.white,
                              fontSize: 20,
                              fontWeight: FontWeight.bold),
                        )
                      ],
                    ),
                    Container(
                      padding: const EdgeInsets.all(15),
                      child: ReadMoreText(
                        content2,
                        trimLines: 58,
                        textAlign: TextAlign.justify,
                        trimMode: TrimMode.Line,
                        lessStyle: const TextStyle(
                          fontWeight: FontWeight.bold,
                          color: Colors.white,
                        ),
                        moreStyle: const TextStyle(
                          fontWeight: FontWeight.bold,
                          color: Colors.white,
                        ),
                        style: const TextStyle(
                            fontSize: 16, height: 1.5, color: Colors.white),
                      ),
                    ),
                    Row(
                      children: [
                        SizedBox(
                          width: width1 * 0.04,
                        ),
                        const Text(
                          'Conatct us',
                          style: TextStyle(
                              color: Colors.white,
                              fontSize: 20,
                              fontWeight: FontWeight.bold),
                        )
                      ],
                    ),
                    Container(
                      padding: const EdgeInsets.all(15),
                      child: ReadMoreText(
                        content3,
                        trimLines: 58,
                        textAlign: TextAlign.justify,
                        trimMode: TrimMode.Line,
                        lessStyle: const TextStyle(
                          fontWeight: FontWeight.bold,
                          color: Colors.white,
                        ),
                        moreStyle: const TextStyle(
                          fontWeight: FontWeight.bold,
                          color: Colors.white,
                        ),
                        style: const TextStyle(
                            fontSize: 16, height: 1.5, color: Colors.white),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
